### PR TITLE
final front-end updates .. (team : return0;)

### PR DESCRIPTION
**Pull request by Aya-Alabrash**

### CODE REVIEW

**Comment by M3kH** [comment]
Can we use `SVG` for the icons?
Also could we

**Comment by gisaac85** [comment]
Maartje that your PR has something wrong with TRAVIS !

**Comment by M3kH** [comment]
I see great work here! 🎉
But although I see something that can be improved.

So here comes a tip since I can imagine that you're are not familiar with *VueJS*.
When you want to refer to a *DOM* object in Vue you can bind it in your component with the ref attribute: https://vuejs.org/v2/api/#ref

 So when you're doing something like this:
```
<input id="myAmazingID" />
...
documet.getElementById('myAmazingID');
```
you instead can do something like this:
```
<input ref="myAmazing" />
...
// And then use in your component like:
this.$refs.myAmazing
```

I hope this helps :-)
Keep the amazing good work here and let's merge it!

**Comment by mkruijt** [comment]
Dear team, good job 🌈!

Last Fixes:
- Show ✋when hover over something you can click (for example file upload)
- *Give feedback about upload Rules:*
- For example here I uploaded a file and the radio button is disabled. I would like to see a better visual indication (Change text color of "If you don't have a cv" in to grey for example) that you can't select this option anymore:
screen shot 2018-08-14 at 18 16 29
- Same counts for the other way around:
here I selected the "I do not have a motivation letter" radio button. The upload is disabled = awesome. But it does not give me any indication that I can't use that anymore, which can cause frustration:
screen shot 2018-08-14 at 18 22 10
- Maybe just change this into: You have successfully submitted your motivation letter? (also remove the header?)
screen shot 2018-08-14 at 18 26 25

- Great what you did with Sass
- I see you implemented some of Mauro's feedback about manipulating dom objects in vue, awesome.

Let's fix the above small things and merge 💥🌼

**Pull request merged**
